-- Clients table
-- ========================================================================================

create table clients(id                number generated by default as identity primary key,
                     name              varchar2(128) not null,
                     registration_date date default sysdate);
        
-- ========================================================================================                    
-- Purchases table
-- ========================================================================================

create table purchases(id            number generated by default as identity primary key,
                       client_id     number not null, 
                       purchase_date date default sysdate,
                       amount        number(10, 2) check (amount > 0),
                       bonus_earned  number default 0,
                       constraint fk_purchases_client foreign key (client_id) references clients(id)
                       );
                     
-- ========================================================================================
-- Bonus_transactions  table
-- ========================================================================================

create table bonus_transactions(id              number generated by default as identity primary key,
                               client_id        number not null,
                               transaction_date date default sysdate,
                               bonus_change     number not null,
                               description      varchar2(255),
                               constraint fk_bonus_client foreign key (client_id) references clients(id));
                
-- ========================================================================================
-- Creating indexes to spead up requests
-- ========================================================================================     

create index idx_client_id_purchases_date on purchases(client_id, purchase_date);
create index idx_client_id_transaction_date on bonus_transactions(client_id, transaction_date);
