-- Clients table
-- ========================================================================================

create table clients(id                number generated by default as identity primary key,
                     name              varchar2(128) not null,
                     registration_date date default sysdate);
        
-- ========================================================================================                    
-- Purchases table
-- ========================================================================================

create table purchases(id            number generated by default as identity primary key,
                       client_id     number not null, 
                       purchase_date date default sysdate,
                       amount        number(10, 2) check (amount > 0),
                       bonus_earned  number default 0,
                       constraint fk_purchases_client foreign key (client_id) references clients(id)
                       );
                     
-- ========================================================================================
-- Bonus_transactions  table
-- ========================================================================================

create table bonus_transactions(id              number generated by default as identity primary key,
                               client_id        number not null,
                               transaction_date date default sysdate,
                               bonus_change     number not null,
                               description      varchar2(255),
                               constraint fk_bonus_client foreign key (client_id) references clients(id));
                
-- ========================================================================================
-- Creating indexes to spead up requests
-- ========================================================================================     

create index idx_client_id_purchases_date on purchases(client_id, purchase_date);
create index idx_client_id_transaction_date on bonus_transactions(client_id, transaction_date);

-- ========================================================================================
-- Materialized view for clients statistic
-- ========================================================================================     

create materialized view mv_client_bonus_stats
refresh complete on demand                      -- Refresh
as
select
    c.id as client_id,
    c.name as client_name,
    
    -- Amount of purchases in the last 30 days from current date
    
    coalesce(sum(case
        when p.purchase_date >= sysdate -30 then
            p.amount
        else 
            0
    end), 0) as total_purchase_30d,
    
    -- Number of purchases in the last 30 days 
    
    coalesce(count(case
        when p.purchase_date >= sysdate -30 then
            1
        else
            null
    end), 0) as purchase_count_30d,
    
    -- Total accumulated bonus = amount of earned bonuses - amount written off
    
    coalesce(
        (select sum(bonus_earned) 
         from purchases 
         where client_id = c.id) 
         -
        (select sum(bonus_change) 
         from bonus_transactions  
         where client_id = c.id and bonus_change < 0), 0
    ) as total_bonus
from
    clients c
    left join purchases p
         on   c.id = p.client_id
group by
    c.id, c.name;
